import os

POSTGRES_USER = os.getenv('POSTGRES_USER', "admin")
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD', "password") 
POSTGRES_HOSTNAME = os.getenv('POSTGRES_HOSTNAME', "localhost") 
POSTGRES_PORT = os.getenv('POSTGRES_PORT', "5433") 
POSTGRES_DATABASE = os.getenv('POSTGRES_DATABASE', "imdb")  
DB_URI = f'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOSTNAME}:{POSTGRES_PORT}/{POSTGRES_DATABASE}'

RABBITMQ_USER = os.getenv('RABBITMQ_USER', "admin")
RABBITMQ_PASSWORD = os.getenv('RABBITMQ_PASSWORD', "password") 
RABBITMQ_HOST = os.getenv('RABBITMQ_HOST', "localhost") 
RABBITMQ_PORT = os.getenv('RABBITMQ_PORT', "5672") 
RABBITMQ_URI = f'amqp://{RABBITMQ_USER}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:{RABBITMQ_PORT}'

REDIS_HOST = os.getenv('REDIS_HOST', "127.0.0.1") 
REDIS_PORT = os.getenv('REDIS_PORT', "6379") 
REDIS_URI = f'redis://{REDIS_HOST}:{REDIS_PORT}'

MINIO_ACCESS_KEY = os.getenv('MINIO_ACCESS_KEY', "admin") 
MINIO_SECRET_KEY = os.getenv('MINIO_SECRET_KEY', "password") 
MINIO_HOST = os.getenv('MINIO_HOST', "localhost") 
MINIO_PORT = os.getenv('MINIO_PORT', "9000")
MINIO_URL = f'{MINIO_HOST}:{MINIO_PORT}'