version: '3.5'

services:
  imdb_minio:
    image: minio/minio:RELEASE.2021-03-04T00-53-13Z
    container_name: imdb_minio
    volumes:
      - minio-volume:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
    command: server /data
    networks:
      - imdb-scraping
    restart: always

  imdb_postgres:
    image: postgres:12.6-alpine
    container_name: imdb_postgres
    volumes:
      - imdb-postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=imdb
    ports:
      - "5433:5432"
    networks:
      - imdb-scraping
    restart: always
    healthcheck:
      test: pg_isready -U admin -d imdb -h localhost -q

  imdb_rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    container_name: imdb_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-volume-lib:/var/lib/rabbitmq
      - rabbitmq-volume-log:/var/log/rabbitmq
    networks:
      - imdb-scraping
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q status

  imdb_redis:
    image: redis:6.2.1-alpine3.13
    container_name: imdb_redis
    ports: 
      - 6379:6379
    networks:
      - imdb-scraping
    restart: always
    healthcheck:
      test: redis-cli ping

networks:
  imdb-scraping:
    external:
      name: imdb-scraping

volumes:
    imdb-postgres-volume:
    minio-volume:
    rabbitmq-volume-lib:
    rabbitmq-volume-log:
