version: '3.5'

services:
  minio:
    image: minio/minio:RELEASE.2021-03-04T00-53-13Z
    container_name: minio
    volumes:
      - minio-volume:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
    command: server /data
    networks:
      - pipeline
    restart: always

  postgres:
    image: postgres:12.6-alpine
    container_name: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATA_PG_PASSWORD}
      - POSTGRES_USER=${DATA_PG_USER}
      - POSTGRES_DB=${DATA_PG_DB}
    ports:
      - "5433:5432"
    networks:
      - pipeline
    restart: always
    healthcheck:
      test: pg_isready -U ${DATA_PG_USER} -d ${DATA_PG_DB} -h localhost -q

networks:
  imdb-scraping:
    external:
      name: imdb-scraping

volumes:
    postgres-volume:
    minio-volume: