{
 "title": "Anime",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 10 Best Anime All Time",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  name as \"Name\",\n  rating_count as \"Rating Count\",\n  rating_value as \"Average Rating\"\nFROM imdb.titles\nWHERE rating_count IS NOT NULL\nORDER BY rating_count DESC, rating_value DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 Genres",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT now() as \"time\", genre, COUNT(*) \nFROM imdb.titles_genres\nJOIN imdb.genres ON genre_id = id\nGROUP BY genre\nORDER BY count DESC\nLIMIT 10\n"
    }
   ]
  },
  {
   "title": "Anime Duration",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\t(SELECT COUNT(duration) FROM imdb.titles\r\n\tWHERE duration IS NOT NULL\r\n  \t\tAND duration < 30) as \"Less than 30 minutes\",\r\n\t(SELECT COUNT(duration) FROM imdb.titles\r\n\tWHERE duration IS NOT NULL\r\n  \t\tAND duration BETWEEN 31 AND 60) as \"Between 31 to 60 minutes\",\r\n\t(SELECT COUNT(duration) FROM imdb.titles\r\n\tWHERE duration IS NOT NULL\r\n  \t\tAND duration > 60) as \"Greater than 60 minutes\"\r\n"
    }
   ]
  },
  {
   "title": "Directed Most Titles (Directors)",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT name, COUNT(*) FROM imdb.titles_directors\r\nJOIN imdb.directors ON director_id = id\r\nGROUP BY name"
    }
   ]
  },
  {
   "title": "Most Titles Written (Writers)",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT name, COUNT(*) FROM imdb.titles_writers\r\nJOIN imdb.writers ON writer_id = id\r\nGROUP BY name"
    }
   ]
  },
  {
   "title": "Most Appearances (Stars)",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT name, COUNT(*) FROM imdb.titles_stars\r\nJOIN imdb.stars ON star_id = id\r\nGROUP BY name"
    }
   ]
  }
 ]
}